In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('dataset_multiple_LR.xlsx')
print(df)

    Age  Weight  Blood Pressure
0    52     173             132
1    59     184             143
2    67     194             153
3    73     211             162
4    64     196             154
5    74     220             168
6    54     188             137
7    61     188             149
8    65     207             159
9    46     167             128
10   72     217             166


In [ ]:
data = df.to_numpy()
print(data)

[[ 52 173 132]
 [ 59 184 143]
 [ 67 194 153]
 [ 73 211 162]
 [ 64 196 154]
 [ 74 220 168]
 [ 54 188 137]
 [ 61 188 149]
 [ 65 207 159]
 [ 46 167 128]
 [ 72 217 166]]


In [ ]:
type(data)


numpy.ndarray

In [ ]:
X = data[:,0:2]
print(X)

[[ 52 173]
 [ 59 184]
 [ 67 194]
 [ 73 211]
 [ 64 196]
 [ 74 220]
 [ 54 188]
 [ 61 188]
 [ 65 207]
 [ 46 167]
 [ 72 217]]


In [ ]:
Y = data[:,2].reshape(-1,1)
print(Y)

[[132]
 [143]
 [153]
 [162]
 [154]
 [168]
 [137]
 [149]
 [159]
 [128]
 [166]]


In [ ]:
X0 = np.ones(11).reshape(-1,1)
print(X0)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
X = np.append(X0,X, axis = 1)
print(X)

[[  1.  52. 173.]
 [  1.  59. 184.]
 [  1.  67. 194.]
 [  1.  73. 211.]
 [  1.  64. 196.]
 [  1.  74. 220.]
 [  1.  54. 188.]
 [  1.  61. 188.]
 [  1.  65. 207.]
 [  1.  46. 167.]
 [  1.  72. 217.]]


In [ ]:
print(Y)

[[132]
 [143]
 [153]
 [162]
 [154]
 [168]
 [137]
 [149]
 [159]
 [128]
 [166]]


In [ ]:
def transpose (X):
  result = np.zeros(len(X)*len(X[0])).reshape(len(X[0]),len(X))
  for j in range(len(X)):
    for i in range(len(X[0])):
      result[i,j] = X[j, i]
  return result

In [ ]:
XT = transpose(X)
print(XT)


[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 52.  59.  67.  73.  64.  74.  54.  61.  65.  46.  72.]
 [173. 184. 194. 211. 196. 220. 188. 188. 207. 167. 217.]]


In [ ]:
def matrixMultiplication(A, B):
  result = np.zeros(len(A)*len(A)).reshape(len(A),len(A))
  for i in range(len(A)):
    for j in range(len(A)):
      for k in range(len(A[0])):
        result[i,j] += A[i,k] * B[k,j]
  return result
  

In [ ]:
np.set_printoptions(suppress=True)
A = matrixMultiplication(XT, X)
A

array([[    11.,    687.,   2145.],
       [   687.,  43737., 135458.],
       [  2145., 135458., 421273.]])